drop function if exists public.daily_loop_upsert_weekly(text,date,text,text,text);
drop function if exists public.daily_loop_create_interaction(text,uuid,date,text);
drop function if exists public.daily_loop_create_task(text,text,date,text);
drop function if exists public.daily_loop_set_habit(text,date,text,boolean);
drop function if exists public.daily_loop_upsert_focus(date,text,text,text,text);
drop table if exists public.daily_loop_habit_state;
drop table if exists public.daily_loop_receipts;
drop table if exists public.weekly_focus;
drop table if exists public.daily_focus;
